#!/bin/bash

echo "App directory is $OPENSHIFT_REPO_DIR"
echo "Creating django project for $OPENSHIFT_APP_NAME app"
django-admin startproject ${OPENSHIFT_APP_NAME}site ${OPENSHIFT_REPO_DIR}/

echo "Creating any necessary tables"
#django-admin makemigrations application
django-admin migrate

#echo "Collect static files"
#django-admin collectstatic --noinput
